language: python

python:
  - "2.7"

install:
  - easy_install distribute
  - pip install -r requirements.txt
  - pip install pytest

script:
  - py.test -v --color=yes --exitfirst --showlocals --durations=5
  - python file5.py some args
